let youtubePlayer;
window.subtitleData = [];
let subtitleData = window.subtitleData;
let currentSubtitleIndex = -1;
let isSpeaking = false;
let ttsSpeed = 1.5;
let ttsLanguage = "vi-VN";
let history = [];
let currentVideoUrl = "";
let vocabList = [];
let instantLookupEnabled = true;
let naverLookupEnabled = false;
let ttsVolume = 1.0;
let syncInterval;
let lastSpokenText = "";
let lastSpokenTime = 0;
let lastCheckedTime = 0;
let isManualSeeking = false;
let vocabPauseTTSEnabled = false;
let lastVocabPauseIndex = -1;
let isVocabPauseSpeaking = false;
let subtitleOffset = 0;
let currentVideoFavorites = [];
let vocabTTSMode = false;
let vocabTTSIndex = -1;
let vocabTTSTimeout;
let isVocabTTSPaused = false;
let pausedVocabIndex = -1;
let vocabDisplayMode = false;
